# Generated by Django 2.2.4 on 2019-08-16 08:58

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.CharField(max_length=120, verbose_name='内容')),
                ('overdue_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='过期时间')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('status', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '活动消息',
                'verbose_name_plural': '活动消息',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0120d81a-c004-11e9-8a7a-a45e60bd391f'), editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=240, null=True, verbose_name='账户标识')),
                ('password', models.CharField(blank=True, max_length=240, null=True, verbose_name='加密后的密码')),
                ('nickName', models.CharField(blank=True, max_length=30, null=True, verbose_name='微信昵称')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='国家')),
                ('province', models.CharField(blank=True, max_length=30, null=True, verbose_name='省份')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='城市')),
                ('avatarUrl', models.CharField(default='https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1556192638273&di=9e48e09e7e73eb477a5cd35be672d912&imgtype=0&src=http%3A%2F%2Fhbimg.b0.upaiyun.com%2F701c1c85751c6cf39cc2e6fdaa4b1f5b6763f9504a7df-QHJpd1_fw658', max_length=240, verbose_name='微信头像')),
                ('unionId', models.CharField(blank=True, max_length=90, null=True, verbose_name='唯一 ID')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别')),
                ('status', models.BooleanField(default=True, verbose_name='是否可用')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '微信用户',
                'verbose_name_plural': '微信用户',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickName', models.CharField(blank=True, max_length=20, null=True, verbose_name='员工真实姓名')),
                ('bith', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别')),
                ('is_staff', models.BooleanField(default=True, help_text='指明用户是否可以登录到这个管理站点。', verbose_name='职员状态')),
                ('is_superuser', models.BooleanField(default=False, help_text='无视权限认证，一键拥有超级权限。', verbose_name='是否超级用户')),
                ('password', models.CharField(max_length=240, verbose_name='登录密码')),
                ('status', models.BooleanField(default=True, verbose_name='账号是否可用')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('sex', models.NullBooleanField(verbose_name='性别')),
                ('name', models.CharField(max_length=60, verbose_name='姓名')),
                ('phone', models.CharField(max_length=30, verbose_name='电话')),
                ('contry', models.CharField(max_length=240, verbose_name='国籍')),
                ('birth', models.CharField(max_length=60, verbose_name='出生日期')),
                ('reserve_time', models.CharField(max_length=60, verbose_name='预约时间')),
                ('mark', models.CharField(max_length=240, verbose_name='症状')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appis.Member', verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Done',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('status', models.BooleanField(default=True, verbose_name='数据状态')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appis.Member', verbose_name='用户')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Appis.Order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '完成记录',
                'verbose_name_plural': '完成记录',
            },
        ),
    ]
