# Generated by Django 2.2.4 on 2019-08-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '预约订单', 'verbose_name_plural': '预约订单'},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='gender',
            new_name='sex',
        ),
        migrations.RemoveField(
            model_name='member',
            name='password',
        ),
        migrations.RemoveField(
            model_name='member',
            name='unionId',
        ),
        migrations.RemoveField(
            model_name='member',
            name='username',
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
