# Generated by Django 2.2.4 on 2019-08-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appis', '0002_auto_20190816_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sex',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别'),
        ),
    ]
