# Generated by Django 2.2.4 on 2019-08-20 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appis', '0003_auto_20190816_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_complete',
            field=models.SmallIntegerField(default=1, verbose_name='预约状态'),
        ),
    ]
