# Generated by Django 2.2.4 on 2019-08-20 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Appis', '0004_order_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.CharField(max_length=120, null=True, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='overdue_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=30, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='order',
            name='birth',
            field=models.CharField(max_length=60, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contry',
            field=models.CharField(max_length=240, null=True, verbose_name='国籍'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_complete',
            field=models.SmallIntegerField(default=1, null=True, verbose_name='预约状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='mark',
            field=models.CharField(max_length=240, null=True, verbose_name='症状'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=60, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=30, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reserve_time',
            field=models.CharField(max_length=60, null=True, verbose_name='预约时间'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
