# Generated by Django 2.2.4 on 2019-08-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appis', '0005_auto_20190820_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='openid',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='OpenId'),
        ),
    ]
