# Generated by Django 2.2.4 on 2019-08-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appis', '0006_member_openid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='sex',
            new_name='gender',
        ),
    ]
