# Generated by Django 2.2.4 on 2019-10-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appis', '0008_member_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reserve_date',
            field=models.CharField(max_length=60, null=True, verbose_name='预约日期'),
        ),
    ]
