# Generated by Django 2.2.4 on 2019-10-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appis', '0009_order_reserve_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='openid',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='OpenId'),
        ),
    ]
